In [2]:
import pandas as pd

In [3]:
##from here https://www.kaggle.com/s903124/nhl-playbyplay-data-from-2007
## all play by play info 2007-2020 or 2021

nhl_df = pd.read_csv("/Users/joejohns/Downloads/nhl_pbp20072008.csv")
nhl_df2 = pd.read_csv("/Users/joejohns/Downloads/nhl_shifts20072008.csv")

In [4]:
nhl_df.loc[-10:, :]

,Game_Id,Date,Period,Event,Description,Time_Elapsed,Seconds_Elapsed,Strength,Ev_Zone,Type,...,Away_Score,Home_Score,Away_Goalie,Away_Goalie_Id,Home_Goalie,Home_Goalie_Id,xC,yC,Home_Coach,Away_Coach
0,20001,2007-09-29,1,STOP,RINK REPAIR,0:00,0.0,5x5,NaN,NaN,...,0,0,ILYA BRYZGALOV,8468524.0,JONATHAN BERNIER,8473541.0,NaN,NaN,MARC CRAWFORD,RANDY CARLYLE
1,20001,2007-09-29,1,PSTR,Period Start- Local time: 5:31 BST,0:00,0.0,5x5,NaN,NaN,...,0,0,ILYA BRYZGALOV,8468524.0,JONATHAN BERNIER,8473541.0,NaN,NaN,MARC CRAWFORD,RANDY CARLYLE
2,20001,2007-09-29,1,FAC,ANA won Neu. Zone - ANA #19 MCDONALD vs L.A #1...,0:00,0.0,5x5,Neu,NaN,...,0,0,ILYA BRYZGALOV,8468524.0,JONATHAN BERNIER,8473541.0,0.0,0.0,MARC CRAWFORD,RANDY CARLYLE
3,20001,2007-09-29,1,SHOT,"L.A ONGOAL - 11 KOPITAR, Wrist, Off. Zone, 22 ft.",0:17,17.0,5x5,Off,WRIST SHOT,...,0,0,ILYA BRYZGALOV,8468524.0,JONATHAN BERNIER,8473541.0,-70.0,-11.0,MARC CRAWFORD,RANDY CARLYLE
4,20001,2007-09-29,1,HIT,"ANA #10 PERRY HIT L.A #4 BLAKE, Off. Zone",0:25,25.0,5x5,Off,NaN,...,0,0,ILYA BRYZGALOV,8468524.0,JONATHAN BERNIER,8473541.0,NaN,NaN,MARC CRAWFORD,RANDY CARLYLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382953,30416,2008-06-04,3,STOP,GOALIE STOPPED,19:26,1166.0,5x5,NaN,NaN,...,3,2,CHRIS OSGOOD,8458568.0,NaN,NaN,NaN,NaN,MICHEL THERRIEN,MIKE BABCOCK
382954,30416,2008-06-04,3,FAC,DET won Def. Zone - DET #33 DRAPER vs PIT #87 ...,19:26,1166.0,5x5,Def,NaN,...,3,2,CHRIS OSGOOD,8458568.0,NaN,NaN,69.0,-23.0,MICHEL THERRIEN,MIKE BABCOCK
382955,30416,2008-06-04,3,SHOT,"PIT ONGOAL - 87 CROSBY, Backhand, Off. Zone, 3...",19:59,1199.0,5x5,Off,BACKHAND,...,3,2,CHRIS OSGOOD,8458568.0,NaN,NaN,62.0,14.0,MICHEL THERRIEN,MIKE BABCOCK
382956,30416,2008-06-04,3,PEND,Period End- Local time: 10:42 EDT,20:00,1200.0,5x5,NaN,NaN,...,3,2,CHRIS OSGOOD,8458568.0,NaN,NaN,NaN,NaN,MICHEL THERRIEN,MIKE BABCOCK
382957,30416,2008-06-04,3,GEND,Game End- Local time: 10:46 EDT,20:00,1200.0,-1x-1,NaN,NaN,...,3,2,NaN,NaN,NaN,NaN,NaN,NaN,MICHEL THERRIEN,MIKE BABCOCK

In [11]:
nhl_df["Event"].value_counts()

FAC      74438
SHOT     69945
STOP     53321
HIT      51753
BLOCK    31957
MISS     28925
GIVE     22245
TAKE     18022
PENL     14650
GOAL      7490
PSTR      4393
PEND      4389
GEND      1265
SOC        159
EISTR        3
EIEND        3
Name: Event, dtype: int64

In [12]:
nhl_df.loc[nhl_df["Event"]=='GOAL', ['Date', 'Period', 'Event', 'Description', 'Time_Elapsed',
       'Seconds_Elapsed', 'Strength', 'Ev_Zone', 'Type', 'Ev_Team',
       'Home_Zone', 'xC', 'yC']]

,Date,Period,Event,Description,Time_Elapsed,Seconds_Elapsed,Strength,Ev_Zone,Type,Ev_Team,Home_Zone,xC,yC
36,2007-09-29,1,GOAL,"L.A #13 CAMMALLERI(1), Wrist, Off. Zone, 27 ft...",8:35,515.0,5x3,Off,WRIST SHOT,L.A,Off,-64.0,10.0
131,2007-09-29,2,GOAL,"L.A #4 BLAKE(1), Slap, Off. Zone, 21 ft.Assist...",10:15,615.0,5x4,Off,SLAP SHOT,L.A,Off,69.0,0.0
175,2007-09-29,3,GOAL,"L.A #13 CAMMALLERI(2), Slap, Off. Zone, 27 ft....",1:10,70.0,5x4,Off,SLAP SHOT,L.A,Off,-69.0,17.0
227,2007-09-29,3,GOAL,"ANA #54 RYAN(1), Slap, Off. Zone, 15 ft.Assist...",13:09,789.0,4x5,Off,SLAP SHOT,ANA,Def,75.0,-2.0
258,2007-09-29,3,GOAL,"L.A #26 HANDZUS(1), Tip-In, Off. Zone, 15 ft.A...",19:34,1174.0,4x5,Off,TIP-IN,L.A,Off,-75.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
382680,2008-06-04,1,GOAL,"DET #28 RAFALSKI(4), Wrist, Off. Zone, 32 ft.A...",5:03,303.0,4x5,Off,WRIST SHOT,DET,Def,-61.0,-14.0
382799,2008-06-04,2,GOAL,"DET #51 FILPPULA(5), Backhand, Off. Zone, 12 f...",8:07,487.0,5x5,Off,BACKHAND,DET,Def,81.0,-8.0
382848,2008-06-04,2,GOAL,"PIT #71 MALKIN(10), Slap, Off. Zone, 30 ft.Ass...",15:26,926.0,5x4,Off,SLAP SHOT,PIT,Off,-62.0,-11.0
382900,2008-06-04,3,GOAL,"DET #40 ZETTERBERG(13), Snap, Off. Zone, 38 ft...",7:36,456.0,5x5,Off,SNAP SHOT,DET,Def,-58.0,-22.0
382947,2008-06-04,3,GOAL,"PIT #18 HOSSA(12), Slap, Off. Zone, 20 ft.Assi...",18:33,1113.0,5x4,Off,SLAP SHOT,PIT,Off,70.0,-3.0

In [14]:
nhl_df2.head(50)

,Game_Id,Period,Team,Player,Player_Id,Start,End,Duration,Date
0,20001,1,ANA,COREY PERRY,8470621.0,0.0,39.0,39.0,2007-09-29
1,20001,1,ANA,CHRIS KUNITZ,8470543.0,0.0,39.0,39.0,2007-09-29
2,20001,1,ANA,ANDY MCDONALD,8468434.0,0.0,39.0,39.0,2007-09-29
3,20001,1,ANA,SEAN O'DONNELL,8458637.0,0.0,39.0,39.0,2007-09-29
4,20001,1,ANA,CHRIS PRONGER,8459424.0,0.0,39.0,39.0,2007-09-29
5,20001,1,ANA,ILYA BRYZGALOV,8468524.0,0.0,1200.0,1200.0,2007-09-29
6,20001,1,L.A,ROB BLAKE,8445550.0,0.0,71.0,71.0,2007-09-29
7,20001,1,L.A,ANZE KOPITAR,8471685.0,0.0,41.0,41.0,2007-09-29
8,20001,1,L.A,MIKE CAMMALLERI,8469500.0,0.0,41.0,41.0,2007-09-29
9,20001,1,L.A,LUBOMIR VISNOVSKY,8468598.0,0.0,76.0,76.0,2007-09-29
10,20001,1,L.A,DUSTIN BROWN,8470606.0,0.0,41.0,41.0,2007-09-29
11,20001,1,L.A,JONATHAN BERNIER,8473541.0,0.0,493.0,493.0,2007-09-29
12,20001,1,ANA,TODD BERTUZZI,8459444.0,39.0,106.0,67.0,2007-09-29
13,20001,1,ANA,SHANE HNIDY,8460661.0,39.0,84.0,45.0,2007-09-29
14,20001,1,ANA,RYAN GETZLAF,8470612.0,39.0,111.0,72.0,2007-09-29
15,20001,1,ANA,FRANCOIS BEAUCHEMIN,8467400.0,39.0,84.0,45.0,2007-09-29
16,20001,1,ANA,BOBBY RYAN,8471676.0,39.0,89.0,50.0,2007-09-29
17,20001,1,L.A,MICHAL HANDZUS,8462129.0,41.0,106.0,65.0,2007-09-29
18,20001,1,L.A,LADISLAV NAGY,8466304.0,41.0,106.0,65.0,2007-09-29
19,20001,1,L.A,JOHN ZEILER,8470113.0,41.0,106.0,65.0,2007-09-29
20,20001,1,L.A,TOM PREISSING,8470575.0,71.0,106.0,35.0,2007-09-29
21,20001,1,L.A,BRAD STUART,8467331.0,76.0,106.0,30.0,2007-09-29
22,20001,1,ANA,JOE DIPENTA,8467387.0,84.0,111.0,27.0,2007-09-29
23,20001,1,ANA,KENT HUSKINS,8467478.0,84.0,111.0,27.0,2007-09-29
24,20001,1,ANA,ROB NIEDERMAYER,8459427.0,89.0,111.0,22.0,2007-09-29
25,20001,1,L.A,ROB BLAKE,8445550.0,106.0,155.0,49.0,2007-09-29
26,20001,1,L.A,ANZE KOPITAR,8471685.0,106.0,155.0,49.0,2007-09-29
27,20001,1,L.A,MIKE CAMMALLERI,8469500.0,106.0,155.0,49.0,2007-09-29
28,20001,1,L.A,LUBOMIR VISNOVSKY,8468598.0,106.0,155.0,49.0,2007-09-29
29,20001,1,L.A,DUSTIN BROWN,8470606.0,106.0,155.0,49.0,2007-09-29
30,20001,1,ANA,SEAN O'DONNELL,8458637.0,111.0,149.0,38.0,2007-09-29
31,20001,1,ANA,TODD MARCHANT,8459587.0,111.0,149.0,38.0,2007-09-29
32,20001,1,ANA,CHRIS PRONGER,8459424.0,111.0,149.0,38.0,2007-09-29
33,20001,1,ANA,TRAVIS MOEN,8468635.0,111.0,155.0,44.0,2007-09-29
34,20001,1,ANA,SHANE HNIDY,8460661.0,149.0,155.0,6.0,2007-09-29
35,20001,1,ANA,RYAN GETZLAF,8470612.0,149.0,155.0,6.0,2007-09-29
36,20001,1,ANA,FRANCOIS BEAUCHEMIN,8467400.0,149.0,188.0,39.0,2007-09-29
37,20001,1,ANA,CHRIS KUNITZ,8470543.0,155.0,188.0,33.0,2007-09-29
38,20001,1,ANA,ANDY MCDONALD,8468434.0,155.0,188.0,33.0,2007-09-29
39,20001,1,ANA,KENT HUSKINS,8467478.0,155.0,188.0,33.0,2007-09-29
40,20001,1,L.A,JACK JOHNSON,8471677.0,155.0,188.0,33.0,2007-09-29
41,20001,1,L.A,ALEX FROLOV,8468500.0,155.0,188.0,33.0,2007-09-29
42,20001,1,L.A,JAROSLAV MODRY,8457403.0,155.0,188.0,33.0,2007-09-29
43,20001,1,L.A,LADISLAV NAGY,8466304.0,155.0,188.0,33.0,2007-09-29
44,20001,1,ANA,SEAN O'DONNELL,8458637.0,188.0,233.0,45.0,2007-09-29
45,20001,1,ANA,TODD MARCHANT,8459587.0,188.0,233.0,45.0,2007-09-29
46,20001,1,ANA,CHRIS PRONGER,8459424.0,188.0,223.0,35.0,2007-09-29
47,20001,1,ANA,ROB NIEDERMAYER,8459427.0,188.0,233.0,45.0,2007-09-29
48,20001,1,L.A,BRAD STUART,8467331.0,188.0,245.0,57.0,2007-09-29
49,20001,1,L.A,DEREK ARMSTRONG,8459064.0,188.0,224.0,36.0,2007-09-29